### ISSUE TITLE
How to extract the collocations dataset from a specific text corpus like English Gigaword?

### ISSUE THREAD

**Issue by jacklanda** [luisespinosaanke/lexicalcollocations#1]
I would like to ask how to extract the collocations dataset from a specific text corpus like English Gigaword? Is there any code implementation released now? Thanks.

**Comment by luisespinosaanke** [comment]
We discuss a bit how that can be done here https://arxiv.org/abs/2205.11456 - Essentially starting from English and using Reverso + pos tagging + manual filtering. Hope this helps!

**Comment by jacklanda** [comment]
> We discuss a bit how that can be done here https://arxiv.org/abs/2205.11456 - Essentially starting from English and using Reverso + pos tagging + manual filtering. Hope this helps!

I see, thanks :)
